spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    app:
      BankApplication : INFO
    org:
      springframework: INFO
  file:
    path : Reservationlog.log

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: your_email@gmail.com
#    password: your_password
#    properties:
#     mail:
#      smtp:
#       starttl:
#        enable: true
server:
  port: 8000
  servlet:
    context-path: /api
jwt:
  secret: secret
  token:
    validity: 8000000000
# logging:
#   level:
#     org:
#       mapstruct=DEBUG:

